<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Products extends \App\Entity\Products implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image1', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image2', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image3', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image4', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image5', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'purchase_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'location_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'caution_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'is_published', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'locations', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'comments'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'brand', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image1', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image2', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image3', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image4', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'image5', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'purchase_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'location_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'caution_price', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'is_published', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'owner', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'locations', '' . "\0" . 'App\\Entity\\Products' . "\0" . 'comments'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Products $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getBrand(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBrand', []);

        return parent::getBrand();
    }

    /**
     * {@inheritDoc}
     */
    public function setBrand(string $brand): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBrand', [$brand]);

        return parent::setBrand($brand);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage1(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage1', []);

        return parent::getImage1();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage1(string $image1): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage1', [$image1]);

        return parent::setImage1($image1);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage2', []);

        return parent::getImage2();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage2(string $image2): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage2', [$image2]);

        return parent::setImage2($image2);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage3(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage3', []);

        return parent::getImage3();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage3(?string $image3): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage3', [$image3]);

        return parent::setImage3($image3);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage4(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage4', []);

        return parent::getImage4();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage4(?string $image4): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage4', [$image4]);

        return parent::setImage4($image4);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage5(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage5', []);

        return parent::getImage5();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage5(?string $image5): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage5', [$image5]);

        return parent::setImage5($image5);
    }

    /**
     * {@inheritDoc}
     */
    public function getPurchasePrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPurchasePrice', []);

        return parent::getPurchasePrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPurchasePrice(float $purchase_price): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPurchasePrice', [$purchase_price]);

        return parent::setPurchasePrice($purchase_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationPrice', []);

        return parent::getLocationPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocationPrice(float $location_price): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocationPrice', [$location_price]);

        return parent::setLocationPrice($location_price);
    }

    /**
     * {@inheritDoc}
     */
    public function getCautionPrice(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCautionPrice', []);

        return parent::getCautionPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setCautionPrice(float $caution_price): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCautionPrice', [$caution_price]);

        return parent::setCautionPrice($caution_price);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsPublished(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsPublished', []);

        return parent::isIsPublished();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsPublished(bool $is_published): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsPublished', [$is_published]);

        return parent::setIsPublished($is_published);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\App\Entity\User
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(?\App\Entity\User $owner): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$owner]);

        return parent::setOwner($owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?\App\Entity\Category
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(?\App\Entity\Category $category): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocations(): ?\App\Entity\Locations
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocations', []);

        return parent::getLocations();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocations(\App\Entity\Locations $locations): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocations', [$locations]);

        return parent::setLocations($locations);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function addComment(\App\Entity\Comments $comment): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addComment', [$comment]);

        return parent::addComment($comment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeComment(\App\Entity\Comments $comment): \App\Entity\Products
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeComment', [$comment]);

        return parent::removeComment($comment);
    }

}
