<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNfvoLmQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNfvoLmQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNfvoLmQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNfvoLmQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNfvoLmQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'NfvoLmQ',
    'container.build_id' => '826b6ac0',
    'container.build_time' => 1665048099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNfvoLmQ');
