<?php

namespace ContainerNfvoLmQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ApiPlatform\State\CreateProvider' shared service.
     *
     * @return \ApiPlatform\State\CreateProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/State/CreateProvider.php';

        return $container->privates['ApiPlatform\\State\\CreateProvider'] = new \ApiPlatform\State\CreateProvider(($container->privates['api_platform.doctrine.orm.state.item_provider'] ?? $container->load('getApiPlatform_Doctrine_Orm_State_ItemProviderService')));
    }
}
